### ISSUE TITLE
right to left support

### ISSUE THREAD

**Issue by pishguy** [Faltenreich/TextInputView#1]
Hi, this library can be support animation from right to left? that means hint of EditText

**Comment by Faltenreich** [comment]
Yes, right-to-left languages are fully supported as noted in the readme: "Right-to-left input is supported throughout using the Android resource system (res/values-ldrtl). The calculations are flipped in order to respect the inverted alignments."

**Comment by pishguy** [comment]
Thanks @Faltenreich my mean is without changing phone language, for example on English i have right to left ui

**Comment by Faltenreich** [comment]
Yes, you can also do that by using gravity: "The gravity of the embedded EditText may be set to Gravity.START, Gravity.END, Gravity.CENTER - or to the obsolete Gravity.LEFT and Gravity.RIGHT, if you insist. The hint of the TextInputView will adjust accordingly and either be moved to the left or right to make place for the user input."

**Comment by pishguy** [comment]
@Faltenreich Thanks
