### ISSUE TITLE
Custom Values do not work

### ISSUE THREAD

**Issue by rafiip** [Faltenreich/TextInputView#2]
Hi.
Values of : hintPadding and android:tint  does not seem to be working. i work around it for few hours so i'm pretty sure.

**Comment by Faltenreich** [comment]
Do you set those values on the TextInputLayout and not on the embedded EditText? If so, could you please provide a code snippet, so that I may reproduce the problem easier.

**Comment by rafiip** [comment]
Sure . i do it on the TextInputLayout . it always gives me some kind of green/blue-ish color no matter what color code i give in for the tint.i must say that normal text color works ok but tint does not change whatsoever.

```
        <com.faltenreich.textinputview.TextInputView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:overlapAction="push"
            android:layout_marginBottom="16dp"
            android:textColor="#212121"
            android:tint="#e65100"
            hintPadding="32dp"
            >
            <EditText
                android:id="@+id/contact_number"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="شماره‌ی تماس"
                android:layout_gravity="right"
                android:gravity="center"
                android:textSize="16dp"
                android:textColor="#212121"
                android:background="#fafafa"
                android:paddingTop="8dp"
                android:paddingBottom="8dp"
                android:paddingRight="16dp"
                android:inputType="phone"
                />
        </com.faltenreich.textinputview.TextInputView>
```
this is what i use .. let me know if you need more

**Comment by Faltenreich** [comment]
Thank you for the information. I will get back to you as soon as I have more insight on the issue. Stay tuned!

**Comment by Faltenreich** [comment]
Thank you again for reporting this bug. I have fixed this issue with version 1.0.2 which is available right now. Feel free to try the new version and report back. :)

**Comment by rafiip** [comment]
the issue is solved! thank you for this awesome library! I'm using it for a charity app .. just informing you that you are doing a great job!

**Comment by Faltenreich** [comment]
Awesome :) Thank you for your support and good luck on your charity work, it is and will be much appreciated! Best regards from Germany!
